name: Test

on:
  push:
    branches:
      - main

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: irgaly/setup-mint@main
        with:
          mint-directory: example
      - shell: bash -xe {0}
        run: |
          ls -alh /usr/local/bin | grep mint
          mint --version
          mint list
          ls -alh ~/.mint
          ls -alh ~/.mint/bin
          ls -alh ~/.mint/packages/*/build/*
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: irgaly/setup-mint@main
        with:
          mint-directory: example
      - shell: bash -xe {0}
        run: |
          ls -alh /usr/local/bin | grep mint
          mint --version
          mint list
          ls -alh ~/.mint
          ls -alh ~/.mint/bin
          ls -alh ~/.mint/packages/*/build/*
